import requests
from scrapper.headers import replicate_header

class replicateAPI:
    def create_req(prompt, model, version):
        
        json_data = {
            'model': model,
            'version': version,
            'input': {
                'prompt': prompt,
            },
            'stream': True,
            'defaultExample': {
                'completed_at': '2023-12-15T03:03:22.968603Z',
                'created_at': '2023-12-15T03:03:17.248001Z',
                'error': None,
                'id': 'sn55aqdbqxec6blon5cnyeso7y',
                'input': {
                    'top_k': 50,
                    'top_p': 0.9,
                    'prompt': "I have to peel 10+ heads of garlic. What's the best way to all the cloves out of a head of garlic?",
                    'temperature': 0.6,
                    'max_new_tokens': 512,
                    'prompt_template': '<s>[INST] {prompt} [/INST] ',
                    'presence_penalty': 0,
                    'frequency_penalty': 0,
                },
                'logs': 'INFO 12-15 03:03:17 async_llm_engine.py:379] Received request 0: prompt: "<s>[INST] I have to peel 10+ heads of garlic. What\'s the best way to all the cloves out of a head of garlic? [/INST] ", sampling params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.6, top_p=0.9, top_k=50, min_p=0.0, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[\'</s>\'], stop_token_ids=[], ignore_eos=False, max_tokens=512, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt token ids: None.\nINFO 12-15 03:03:17 llm_engine.py:649] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%\nINFO 12-15 03:03:22 llm_engine.py:649] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 81.3 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%\nINFO 12-15 03:03:22 async_llm_engine.py:111] Finished request 0.\ngeneration took 5.707s',
                'metrics': {
                    'predict_time': 5.716247,
                    'total_time': 5.720602,
                },
                'output': [
                    '1',
                    '.',
                    ' First',
                    ',',
                    ' you',
                    "'",
                    'll',
                    ' want',
                    ' to',
                    ' prepare',
                    ' the',
                    ' garlic',
                    ' for',
                    ' pe',
                    'eling',
                    ' by',
                    ' removing',
                    ' the',
                    ' pap',
                    'ery',
                    ' outer',
                    ' layers',
                    '.',
                    ' To',
                    ' do',
                    ' this',
                    ',',
                    ' place',
                    ' the',
                    ' head',
                    ' of',
                    ' garlic',
                    ' on',
                    ' a',
                    ' flat',
                    ' surface',
                    ' with',
                    ' one',
                    ' of',
                    ' the',
                    ' cut',
                    ' ends',
                    ' facing',
                    ' down',
                    '.',
                    ' Using',
                    ' the',
                    ' flat',
                    ' side',
                    ' of',
                    ' a',
                    ' large',
                    ' knife',
                    ',',
                    ' gently',
                    ' tap',
                    ' the',
                    ' garlic',
                    ' to',
                    ' remove',
                    ' the',
                    ' tip',
                    ' of',
                    ' the',
                    ' cl',
                    'ove',
                    '.',
                    ' This',
                    ' will',
                    ' expose',
                    ' the',
                    ' cl',
                    'ove',
                    ' a',
                    ' bit',
                    ',',
                    ' making',
                    ' it',
                    ' easier',
                    ' to',
                    ' pe',
                    'el',
                    '.',
                    '\n',
                    '\n',
                    '2',
                    '.',
                    ' Next',
                    ',',
                    ' place',
                    ' the',
                    ' flat',
                    ' side',
                    ' of',
                    ' the',
                    ' knife',
                    ' on',
                    ' the',
                    ' exposed',
                    ' cl',
                    'ove',
                    ' and',
                    ' apply',
                    ' pressure',
                    ' to',
                    ' press',
                    ' the',
                    ' cl',
                    'ove',
                    ' out',
                    ' of',
                    ' its',
                    ' pap',
                    'ery',
                    ' skin',
                    '.',
                    ' You',
                    ' can',
                    ' also',
                    ' use',
                    ' the',
                    ' side',
                    ' of',
                    ' a',
                    ' chef',
                    "'",
                    's',
                    ' knife',
                    ' or',
                    ' a',
                    ' garlic',
                    ' press',
                    ' if',
                    ' you',
                    ' prefer',
                    '.',
                    '\n',
                    '\n',
                    '3',
                    '.',
                    ' If',
                    ' you',
                    ' don',
                    "'",
                    't',
                    ' want',
                    ' to',
                    ' use',
                    ' a',
                    ' knife',
                    ',',
                    ' you',
                    ' can',
                    ' also',
                    ' pe',
                    'el',
                    ' the',
                    ' garlic',
                    ' by',
                    ' placing',
                    ' the',
                    ' head',
                    ' in',
                    ' a',
                    ' shallow',
                    ' bowl',
                    ' and',
                    ' covering',
                    ' it',
                    ' with',
                    ' the',
                    ' palm',
                    ' of',
                    ' your',
                    ' hand',
                    '.',
                    ' Using',
                    ' the',
                    ' he',
                    'el',
                    ' of',
                    ' your',
                    ' hand',
                    ',',
                    ' gently',
                    ' press',
                    ' down',
                    ' on',
                    ' the',
                    ' garlic',
                    ' while',
                    ' moving',
                    ' it',
                    ' around',
                    ' in',
                    ' the',
                    ' bowl',
                    '.',
                    ' The',
                    ' cl',
                    'oves',
                    ' will',
                    ' pop',
                    ' out',
                    ' of',
                    ' their',
                    ' sk',
                    'ins',
                    ' as',
                    ' you',
                    ' do',
                    ' this',
                    '.',
                    '\n',
                    '\n',
                    '4',
                    '.',
                    ' Altern',
                    'atively',
                    ',',
                    ' you',
                    ' can',
                    ' also',
                    ' ro',
                    'ast',
                    ' the',
                    ' garlic',
                    ' before',
                    ' pe',
                    'eling',
                    '.',
                    ' Pre',
                    'he',
                    'at',
                    ' the',
                    ' oven',
                    ' to',
                    ' ',
                    '3',
                    '5',
                    '0',
                    '°',
                    'F',
                    ' (',
                    '1',
                    '7',
                    '5',
                    '°',
                    'C',
                    ').',
                    ' Cut',
                    ' off',
                    ' the',
                    ' top',
                    ' of',
                    ' the',
                    ' garlic',
                    ' head',
                    ' to',
                    ' expose',
                    ' the',
                    ' cl',
                    'oves',
                    '.',
                    ' D',
                    'ri',
                    'zz',
                    'le',
                    ' the',
                    ' head',
                    ' with',
                    ' oil',
                    ' and',
                    ' wrap',
                    ' it',
                    ' in',
                    ' fo',
                    'il',
                    '.',
                    ' Ro',
                    'ast',
                    ' for',
                    ' about',
                    ' ',
                    '3',
                    '0',
                    '-',
                    '4',
                    '0',
                    ' minutes',
                    ',',
                    ' or',
                    ' until',
                    ' the',
                    ' cl',
                    'oves',
                    ' are',
                    ' soft',
                    ' and',
                    ' golden',
                    ' brown',
                    '.',
                    ' The',
                    ' sk',
                    'ins',
                    ' will',
                    ' come',
                    ' off',
                    ' easily',
                    ' after',
                    ' ro',
                    'asting',
                    '.',
                    '\n',
                    '\n',
                    '5',
                    '.',
                    ' If',
                    ' you',
                    "'",
                    're',
                    ' pe',
                    'eling',
                    ' a',
                    ' lot',
                    ' of',
                    ' garlic',
                    ' at',
                    ' once',
                    ',',
                    ' you',
                    ' can',
                    ' also',
                    ' bl',
                    'anch',
                    ' it',
                    ' to',
                    ' make',
                    ' the',
                    ' process',
                    ' easier',
                    '.',
                    ' Bring',
                    ' a',
                    ' pot',
                    ' of',
                    ' water',
                    ' to',
                    ' a',
                    ' bo',
                    'il',
                    ',',
                    ' then',
                    ' add',
                    ' the',
                    ' whole',
                    ' heads',
                    ' of',
                    ' garlic',
                    '.',
                    ' Bl',
                    'anch',
                    ' for',
                    ' about',
                    ' ',
                    '3',
                    '0',
                    ' seconds',
                    ',',
                    ' then',
                    ' transfer',
                    ' the',
                    ' garlic',
                    ' to',
                    ' an',
                    ' ice',
                    ' bath',
                    ' to',
                    ' cool',
                    '.',
                    ' The',
                    ' sk',
                    'ins',
                    ' will',
                    ' come',
                    ' off',
                    ' easily',
                    ' after',
                    ' bl',
                    'anch',
                    'ing',
                    '.',
                    '\n',
                    '\n',
                    '6',
                    '.',
                    ' Once',
                    ' you',
                    "'",
                    've',
                    ' removed',
                    ' the',
                    ' cl',
                    'oves',
                    ' from',
                    ' the',
                    ' head',
                    ' of',
                    ' garlic',
                    ',',
                    ' you',
                    ' can',
                    ' further',
                    ' min',
                    'ce',
                    ' or',
                    ' chop',
                    ' them',
                    ' as',
                    ' needed',
                    ' for',
                    ' your',
                    ' recipe',
                    '.',
                    '\n',
                    '\n',
                    '7',
                    '.',
                    ' Finally',
                    ',',
                    ' if',
                    ' you',
                    ' find',
                    ' that',
                    ' you',
                    ' frequently',
                    ' use',
                    ' a',
                    ' lot',
                    ' of',
                    ' garlic',
                    ',',
                    ' consider',
                    ' investing',
                    ' in',
                    ' a',
                    ' garlic',
                    ' press',
                    ' or',
                    ' a',
                    ' garlic',
                    ' pe',
                    'eler',
                    ' to',
                    ' make',
                    ' the',
                    ' process',
                    ' faster',
                    ' and',
                    ' easier',
                    '.',
                    '',
                ],
                'started_at': '2023-12-15T03:03:17.252356Z',
                'status': 'succeeded',
                'urls': {
                    'stream': 'https://streaming-api.svc.us.c.replicate.net/v1/predictions/sn55aqdbqxec6blon5cnyeso7y',
                    'get': 'https://api.replicate.com/v1/predictions/sn55aqdbqxec6blon5cnyeso7y',
                    'cancel': 'https://api.replicate.com/v1/predictions/sn55aqdbqxec6blon5cnyeso7y/cancel',
                },
                'model': 'mistralai/mistral-7b-instruct-v0.2',
                'version': 'f5701ad84de5715051cb99d550539719f8a7fbcf65e0e62a3d1eb3f94720764e',
                'webhook_completed': None,
            },
        }

        response = requests.post('https://homepage.replicate.com/api/prediction', headers=replicate_header, json=json_data)
        
        result = response.json()["id"]
        
        return result
    
    def get_res(id):

        response = requests.get(f'https://homepage.replicate.com/api/poll?id={id}', headers=replicate_header)
        
        result = response.json()
        
        return result
        

